export const GET_WORKFLOW_START = "GET_WORKFLOW_START";
export const GET_WORKFLOW_SUCCESS = "GET_WORKFLOW_SUCCESS";
export const GET_WORKFLOW_FAIL = "GET_WORKFLOW_FAIL";
export const GET_WORKFLOW_CLEANUP = "GET_WORKFLOW_CLEANUP";

export const SAVE_WORKFLOW_START = "SAVE_WORKFLOW_START";
export const SAVE_TEMP_WORKFLOW = "SAVE_TEMP_WORKFLOW";
export const SAVE_WORKFLOW_SUCCESS = "SAVE_WORKFLOW_SUCCESS";
export const SAVE_WORKFLOW_FAIL = "SAVE_WORKFLOW_FAIL";
export const SAVE_WORKFLOW_CLEANUP = "SAVE_WORKFLOW_CLEANUP";

